name: Bug report
description: Reportar comportamento incorreto
title: "[bug]: "
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que aconteceu vs o esperado
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versão
      placeholder: "1.4.5"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      render: shell
