name: Feature request
description: Sugerir nova funcionalidade ou melhoria
title: "[feat]: "
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema ou oportunidade
      description: Qual necessidade esta feature atende?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solução proposta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
